spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    # ✅ 운영에서는 환경변수로 MySQL 연결
    # ✅ 로컬 개발에서는 H2 DB 기본값 사용
    url: ${DB_URL:jdbc:h2:mem:testdb}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}

  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:create}
    open-in-view: false

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true

  observations:
    http:
      server:
        requests:
          record-exceptions: true  # ✅ 예외도 메트릭으로 기록

  mvc:
    throw-exception-if-no-handler-found: true # 없는 경로 요청 시 DispatcherServlet이 404 예외 던짐
  web:
    resources:
      add-mappings: false # 정적 리소스 매핑 비활성화

jwt:
  secret: ${JWT_SECRET:defaultBase64EncodedSecret}
  access-token-validity-in-seconds: ${JWT_ACCESS_TOKEN_VALIDITY:604800}  
  refresh-token-validity-in-seconds: ${JWT_REFRESH_TOKEN_VALIDITY:604800} 

logging:
  level:
    root: INFO
